site_name: My Docs
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
plugins:
  - search
  - mermaid2
extra_javascript:
  - https://unpkg.com/mermaid@9.4.3/dist/mermaid.min.js
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
extra:
  generator: false
nav:
- 首页: index.md
